# Feature Selection:
### 1- using `VarianceThreshold`:

In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import VarianceThreshold

In [2]:
df = pd.read_csv('./images_chiffres_codees_niveau_de_gris.csv')
df.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [9]:
filter = VarianceThreshold(0.3)
result = filter.fit_transform(df.iloc[:,1:])

In [10]:
result

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [18]:
X = df.iloc[:,1:]
X.var(axis=0).sort_values(ascending=False)

pixel437    12835.951642
pixel461    12835.805026
pixel433    12789.630378
pixel406    12787.678149
pixel434    12759.003386
                ...     
pixel308        0.000000
pixel335        0.000000
pixel336        0.000000
pixel363        0.000000
pixel783        0.000000
Length: 784, dtype: float64

In [30]:
filter.get_support()

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

### 2-using `SelectKBest`:

In [31]:
from sklearn.feature_selection import chi2, SelectKBest

In [35]:
X = df.iloc[:,1:]
Y = df.label
chi2(X,Y)

(array([           nan,            nan,            nan,            nan,
                   nan,            nan,            nan,            nan,
                   nan,            nan,            nan,            nan,
                   nan,            nan,            nan,            nan,
                   nan,            nan,            nan,            nan,
                   nan,            nan,            nan,            nan,
                   nan,            nan,            nan,            nan,
                   nan,            nan,            nan,            nan,
                   nan,            nan,            nan,            nan,
                   nan, 1.98067692e+03, 3.66955769e+03, 2.98870000e+03,
        2.60412272e+03, 1.81478579e+03, 2.56676107e+03, 3.50398000e+03,
        3.31941071e+03, 1.84968097e+03, 2.24594615e+03, 3.71376923e+02,
        2.12215385e+03, 9.72653846e+02,            nan,            nan,
                   nan,            nan,            nan,         

In [37]:
filter_2 = SelectKBest(chi2, k=600)
print(X.shape)
fited_data = filter_2.fit_transform(X,Y)

(2559, 784)


In [38]:
fited_data.shape

(2559, 600)

### 3- using `SelectFromModel`:

In [39]:
from sklearn.feature_selection import SelectFromModel
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression


In [40]:
model_1 = KNeighborsClassifier()
model_2 = DecisionTreeClassifier()
model_3 = LogisticRegression()

In [ ]:
selector_1 = SelectFromModel(model_2, threshold='mean')